<?php
/** @var Panda\Blog\Block\PostBlock $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Panda\Blog\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
$pagerBlock = $block->getChildBlock('block_pager');
$limit = $block->getItemsPerPage();
$collection = $postVm->getPosts($limit);

?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$imageUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'img.png';
?>
<div class="blog-post-list">
    <h1><?= __('Blog posts') ?></h1>
    <div class="post-grid-container">
        <?php foreach ($collection as $post): ?>
            <div class="post-grid-item">
                <img src="<?php echo $imageUrl; ?>" alt="1">
                <div class="post-name"><?php echo $post->getTitle(); ?></div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if ($pagerBlock): ?>
        <?= $postVm->getPager($collection, $pagerBlock) ?>
    <?php endif; ?>
</div>
